"""
example_usage.py
----------------
Full worked example: 4 agents working on auth, API, billing, and UI.
Each agent is simulated by a thread that writes files and signals DONE.

In a real system, replace the `simulate_agent_work` function with your
AI agent invocation (Claude API call, LangChain agent, etc.).

Run from the repo root:
    python example_usage.py --repo /path/to/your/repo
"""

from __future__ import annotations
import argparse
import logging
import threading
import time
from pathlib import Path

from git_agent_coordinator import (
    Agent,
    AgentStatus,
    CoordinatorConfig,
    CoordinatorEvents,
    WorktreeCoordinator,
)
from git_agent_coordinator.models import MergeCheckResult

# ------------------------------------------------------------------
# Logging setup
# ------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(name)s — %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("example")


# ------------------------------------------------------------------
# Custom event hooks (optional — replace with Slack/webhook/etc.)
# ------------------------------------------------------------------

class NotifyingEvents(CoordinatorEvents):
    def on_conflict_detected(self, result: MergeCheckResult, agents) -> None:
        agent_ids = [a.id for a in agents]
        log.warning(
            "⚠️  CONFLICT detected between %s ↔ %s on files: %s",
            result.base_ref, result.target_ref, result.conflicting_files
        )
        # In production: post to Slack, open a GitHub issue, etc.

    def on_agent_paused(self, agent, reason: str) -> None:
        log.warning("⏸  Agent '%s' paused — %s", agent.id, reason)
        # In production: send a signal to the agent process to stop committing

    def on_agent_resumed(self, agent) -> None:
        log.info("▶️  Agent '%s' resumed after rebase", agent.id)
        # In production: signal the agent process it may continue

    def on_merge_complete(self, agent) -> None:
        log.info("✅  Agent '%s' merged into main", agent.id)

    def on_merge_cascade(self, rebased_agents) -> None:
        ids = [a.id for a in rebased_agents]
        log.info("🔄  Cascade rebase applied to: %s", ids)


# ------------------------------------------------------------------
# Simulated agent work
# Replace this with your actual AI agent invocation.
# ------------------------------------------------------------------

def simulate_agent_work(agent: Agent, coordinator: WorktreeCoordinator) -> None:
    """
    Pretend to be an AI agent:
    - Write some files in the worktree
    - Sleep to simulate thinking/writing time
    - Call coordinator.mark_agent_done() when finished

    In a real system this function would call your AI agent API and
    let the agent write files into `agent.worktree_path`.
    """
    log.info("🤖  Agent '%s' starting work in %s", agent.id, agent.worktree_path)

    # Write a placeholder file to each owned prefix to simulate real work
    for prefix in agent.owned_files:
        target = agent.worktree_path / prefix
        target.mkdir(parents=True, exist_ok=True)
        (target / "implementation.py").write_text(
            f"# Generated by {agent.id}\n# Branch: {agent.branch}\n"
            f"# Owned files: {agent.owned_files}\n"
        )

    # Commit the work (in a real system, the AI agent does this)
    import subprocess
    subprocess.run(["git", "add", "-A"], cwd=agent.worktree_path, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", f"feat: {agent.id} initial implementation"],
        cwd=agent.worktree_path, capture_output=True
    )

    # Signal the coordinator that this agent is finished
    coordinator.mark_agent_done(agent.id)
    log.info("🏁  Agent '%s' finished — waiting for coordinator to merge", agent.id)


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------

def main(repo_path: Path) -> None:
    # ---- Define the agents and their file ownership ----
    agents = [
        Agent(
            id="agent-A",
            branch="feature/auth",
            worktree_path=repo_path.parent / "ws-agent-A",
            owned_files=["src/auth/", "src/middleware/", "tests/auth/"],
            depends_on=[],                # no prerequisites — lands first
        ),
        Agent(
            id="agent-C",
            branch="feature/api",
            worktree_path=repo_path.parent / "ws-agent-C",
            owned_files=["src/api/routes/", "src/api/schema.py", "tests/api/"],
            depends_on=["agent-A"],       # needs auth tokens defined first
        ),
        Agent(
            id="agent-B",
            branch="feature/billing",
            worktree_path=repo_path.parent / "ws-agent-B",
            owned_files=["src/payments/", "src/billing/", "tests/billing/"],
            depends_on=["agent-C"],       # calls the API layer
        ),
        Agent(
            id="agent-D",
            branch="feature/ui",
            worktree_path=repo_path.parent / "ws-agent-D",
            owned_files=["src/ui/components/", "src/ui/hooks/", "tests/ui/"],
            depends_on=["agent-C", "agent-B"],  # consumes both API and billing
        ),
    ]

    config = CoordinatorConfig(
        repo_path=repo_path,
        main_branch="main",
        check_every_n_commits=5,        # check for conflicts every 5 commits
        poll_interval_seconds=10.0,
        max_drift_commits=15,
        auto_rebase=True,
        squash_on_merge=True,
    )

    coordinator = WorktreeCoordinator(config, agents, events=NotifyingEvents())

    # ---- Print the planned merge order before we start ----
    print("\n" + coordinator.dag.describe() + "\n")

    # ---- Setup: create worktrees and register file ownership ----
    coordinator.setup()

    # ---- Launch agent threads (simulated AI work) ----
    # In production: spawn agent processes, or call an async agent runner.
    threads = []
    for agent in agents:
        t = threading.Thread(
            target=simulate_agent_work,
            args=(agent, coordinator),
            name=f"agent-{agent.id}",
            daemon=True,
        )
        threads.append(t)

    # Stagger agent starts slightly so they're not all committing simultaneously
    for i, t in enumerate(threads):
        time.sleep(i * 2)
        t.start()

    # ---- Start the coordinator loop (blocks until all agents are merged) ----
    coordinator.run()

    print("\n✅  All agents merged. Final worktrees cleaned up.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Multi-agent git worktree coordinator demo")
    parser.add_argument("--repo", type=Path, required=True, help="Path to the git repo")
    args = parser.parse_args()

    main(args.repo.resolve())
